# Generated by Django 2.0.6 on 2018-08-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180818_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='credit_number',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
