# Generated by Django 2.0.6 on 2018-08-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180818_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
