# Generated by Django 2.0.6 on 2018-07-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180715_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('?',)},
        ),
    ]
