# Generated by Django 2.1.4 on 2019-04-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20190407_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biditems',
            name='won',
        ),
        migrations.AddField(
            model_name='bidders',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
