# Generated by Django 2.1.4 on 2019-04-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20190407_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='biditems',
            name='time',
            field=models.BooleanField(default=False),
        ),
    ]
