# Generated by Django 2.1.4 on 2019-05-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_biditems_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidders',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
