# Generated by Django 2.0.6 on 2018-07-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180712_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
