# Generated by Django 2.0.6 on 2018-07-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180712_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='specification_of_product',
            field=models.TextField(null=True),
        ),
    ]
