# Generated by Django 2.0.6 on 2018-07-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180712_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address_of_delivery',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
