# Generated by Django 2.0.6 on 2018-07-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
