# Generated by Django 2.0.6 on 2018-07-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180715_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'ordering': ('-created',)},
        ),
    ]
