# Generated by Django 2.0.6 on 2018-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180716_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
