# Generated by Django 2.0.6 on 2018-07-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_ordernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
