# Generated by Django 2.0.6 on 2018-07-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20180717_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='user',
        ),
    ]
