# Generated by Django 2.0.6 on 2018-07-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_remove_orderdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='phone_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
