# Generated by Django 2.0.6 on 2018-07-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_orderdetails_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
