# Generated by Django 2.0.6 on 2018-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_ordernotification_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-quantity',)},
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='address_of_delivery',
            field=models.CharField(choices=[('Ng', 'Ngara'), ('Am', 'Ambassadors'), ('Rw', 'Railways'), ('Up', 'Uhuru park')], default='Ngara', max_length=50),
        ),
    ]
