# Generated by Django 2.0.6 on 2018-07-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_orderdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
