# Generated by Django 2.0.6 on 2018-07-25 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20180725_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='phone_number',
            field=models.PositiveIntegerField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='phone number must be entered in the format +254... up to 12 digits allowed', regex='^\\+?1?\\d{254,12}$')]),
        ),
    ]
