# Generated by Django 2.0.6 on 2018-08-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_auto_20180726_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='status',
            new_name='approved',
        ),
    ]
