# Generated by Django 2.1.4 on 2019-05-18 07:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0042_auto_20180823_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='phone number must be entered in the format +254... up to 12 digits allowed', regex='^\\+?1?\\d{2,12}$')]),
        ),
    ]
